<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KKJRBSE" failures="1" tests="1" name="Test" time="6.401" errors="0" timestamp="2024-11-15T18:53:38 IST">
  <testcase classname="testCases.TC_LoginDDT" name="verifyLogin_DDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at utilities.Dataprovider.getData(Dataprovider.java:25)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin_DDT -->
</testsuite> <!-- Test -->
